name: dinosaur
description: 怪兽 Flutter
publish_to: 'none'
version: 1.0.1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  app_base:
    path: ./library/app_base
  image_cropper:
    path: ./library/cropper
  cupertino_icons: ^1.0.6
  flutter_advanced_seekbar: ^0.0.2
  circular_countdown_timer: ^0.2.3
  share_plus: ^7.2.2
  uni_links: ^0.5.1
  loading_animation_widget: ^1.2.1
  connectivity_plus: ^6.0.1
  flutter_reorderable_grid_view: ^4.0.0
  status_bar_control: ^3.2.1
#  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1
  gradient_slider: ^1.0.2
  vibration: ^1.8.4
  pinput: ^4.0.0
  image: ^4.1.7
  flutter_native_splash: ^2.4.0
  flutter_sound: ^9.4.11
  flutter_sound_platform_interface: 9.4.11
  audio_session: ^0.1.6
  sensors_plus: ^4.0.2
  banner_carousel: ^1.2.1
  font_awesome_flutter: ^10.7.0
  flutter_datetime_picker_plus: ^2.2.0
  visibility_detector: ^0.4.0+2
  audio_wave: ^0.1.5
  city_pickers: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
